# Training Basics
# val_interval: 10
# val_interval: 5
val_interval: 1

# lr: 3e-4
lr: 1e-3
seed: 42
subject: "1ABA005_3.0x3.0x3.0_resampled" # for train_single
subjects: ["1ABA005_3.0x3.0x3.0_resampled", "1ABA005_3.0x3.0x3.0_resampled"]
# subjects: ["1ABA005_3.0x3.0x3.0_resampled", "1HNA001_3.0x3.0x3.0_resampled", "1THA001_3.0x3.0x3.0_resampled", "1ABA005_3.0x3.0x3.0_resampled"]
# subjects: null # for train_multi
no_wandb: false

epochs_mlp: 500
epochs_cnn: 200

# Model Configuration
# model_type: "cnn"      # Options: "mlp", "cnn"
model_type: "MLP"
use_seg: false
seg_name: "labels_moved.nii.gz"
# dropout: 0.2
dropout: 0.0

augment: false
patch_size: 96
# patches_per_volume: 500
patches_per_volume: 100
# patches_per_volume: 50
# patches_per_volume: 20

# MLP Config
# mlp_batch_size: 16384 # Points to sample per patch (feature vector batch)
# mlp_batch_size: 131072
# mlp_batch_size: 262144
mlp_batch_size: 884736
no_fourier: false      # If true, disables Fourier features for MLP
sigma: 5.0            # Fourier feature scale
mlp_depth: 4   
mlp_hidden: 256  

# CNN Config
cnn_batch_size: 1   
cnn_depth: 9          
cnn_hidden: 128       
final_activation: "sigmoid"

# Loss Weights
l1_w: 1.0
l2_w: 0.0
ssim_w: 1.0